name: Release
on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '1.0.6-test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"

    - name: Publish to Apache Maven Central
      run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy
      env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
