name: Release
on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '1.0.6-test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - uses: actions/checkout@v2

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
          distribution: temurin
          java-version: 11
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}         

    - name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"

    - name: Publish package
      run: mvn --batch-mode clean deploy -P central-deploy -DskipTests=true
      env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}          
