name: Deploy on Maven Central
on:
  push:
    tags:
      - '*'
      
jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Properties File
        run: |
          echo "
             test-email=${{secrets.RECEIVER_EMAIL}}
             test-email-application-password=${{secrets.RECEIVER_EMAIL_PASSWORD}}
             test-email-master-password=${{secrets.SENDER_PASSWORD}}
             sender-test-email=${{secrets.SENDER_TEST_EMAIL}}
             host=${{secrets.SENDER_HOST}}
           " >> src/test/resources/test.properties

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 19
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build, Test & Publish
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/out/artifacts/Java-Utilities_jar/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to the Maven Central Repository
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
